services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: cpa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5449:5432"

  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
