"""New initial

Revision ID: 1b774b480b11
Revises: 
Create Date: 2026-05-16 20:46:07.112645

"""
from typing import Sequence, Union

from alembic import op  # noqa
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b774b480b11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
